// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
// Copyright (C) Leszek Pomianowski and MaterialWPF Contributors.
// All Rights Reserved.

namespace MaterialWPF.UI
{
    /// <summary>
    /// List of all available icons
    /// <para>May be converted to <see langword="char"/> using <see cref="MiconIcons.ToGlyph(MaterialIcon?)"/> or to <see langword="string"/> using <see cref="MiconIcons.ToString(MaterialIcon?)"/></para>
    /// </summary>
    public enum MaterialIcon
    {
        Accept,
        Accident,
        AccidentSolid,
        Accounts,
        ActionCenter,
        ActionCenterAsterisk,
        ActionCenterMirrored,
        ActionCenterNotification,

        ActionCenterNotificationMirrored,
        ActionCenterQuiet,
        ActionCenterQuietNotification,
        Add,
        AddFriend,
        AddRemoteDevice,
        AddSurfaceHub,
        AddTo,

        AdjustHologram,
        Admin,
        Airplane,
        AirplaneSolid,
        AlignCenter,
        AlignLeft,
        AlignRight,
        AllApps,

        AllAppsMirrored,
        Annotation,
        AppIconDefault,
        Apps,
        AreaChart,
        ArrowDown8,
        ArrowLeft8,
        ArrowRight8,

        ArrowUp8,
        AspectRatio,
        Asterisk,
        AsteriskBadge12,
        Attach,
        AttachCamera,
        Audio,
        Back,

        BackMirrored,
        BackSpaceQWERTYLg,
        BackSpaceQWERTYMd,
        BackSpaceQWERTYSm,
        BackToWindow,
        BackgroundToggle,
        Badge,
        BandBattery0,

        BandBattery1,
        BandBattery2,
        BandBattery3,
        BandBattery4,
        BandBattery5,
        BandBattery6,
        Bank,
        BarcodeScanner,

        Battery0,
        Battery1,
        Battery10,
        Battery2,
        Battery3,
        Battery4,
        Battery5,
        Battery6,

        Battery7,
        Battery8,
        Battery9,
        BatteryCharging0,
        BatteryCharging1,
        BatteryCharging10,
        BatteryCharging2,
        BatteryCharging3,

        BatteryCharging4,
        BatteryCharging5,
        BatteryCharging6,
        BatteryCharging7,
        BatteryCharging8,
        BatteryCharging9,
        BatterySaver0,
        BatterySaver1,

        BatterySaver10,
        BatterySaver2,
        BatterySaver3,
        BatterySaver4,
        BatterySaver5,
        BatterySaver6,
        BatterySaver7,
        BatterySaver8,

        BatterySaver9,
        BatteryUnknown,
        Beta,
        BidiLtr,
        BidiRtl,
        BlockContact,
        Blocked,
        BlueLight,

        Bluetooth,
        BodyCam,
        Bold,
        BoldF,
        BoldG,
        BoldKorean,
        BoldN,
        BoldRussion,

        Bookmarks,
        BookmarksMirrored,
        Brightness,
        Broom,
        BrowsePhotos,
        BrushSize,
        Bug,
        BuildingEnergy,

        BulletedList,
        BulletedListMirrored,
        Bullseye,
        BumperLeft,
        BumperRight,
        Bus,
        BusSolid,
        ButtonA,

        ButtonB,
        ButtonMenu,
        ButtonView2,
        ButtonX,
        ButtonY,
        CC,
        CCEuro,
        CCJapan,

        Cafe,
        Calculator,
        CalculatorAddition,
        CalculatorBackspace,
        CalculatorDivide,
        CalculatorEqualTo,
        CalculatorMultiply,
        CalculatorNegate,

        CalculatorPercentage,
        CalculatorSquareroot,
        CalculatorSubtract,
        Calendar,
        CalendarDay,
        CalendarMirrored,
        CalendarReply,
        CalendarSolid,

        CalendarWeek,
        CallForwardInternational,
        CallForwardInternationalMirrored,
        CallForwardRoaming,
        CallForwardRoamingMirrored,
        CallForwarding,
        CallForwardingMirrored,
        CalligraphyFill,

        CalligraphyPen,
        Calories,
        Camera,
        Cancel,
        Caption,
        Car,
        CaretBottomRightSolidCenter8,
        CaretDownSolid8,

        CaretLeftSolid8,
        CaretRight8,
        CaretRightSolid8,
        CaretUpSolid8,
        CashDrawer,
        CellPhone,
        Certificate,
        CharacterAppearance,

        Characters,
        ChatBubbles,
        CheckList,
        CheckMark,
        Checkbox,
        Checkbox14,
        CheckboxComposite,
        CheckboxComposite14,

        Color,
        GridView,

        Input
    }
}
